// On s'assure que tout le code HTML est chargé avant d'exécuter le script
document.addEventListener('DOMContentLoaded', () => {
    // Récupération des éléments du bouton et du menu déroulant
    const addFilesBtn = document.getElementById('addFilesBtn');
    const filesDropdown = document.getElementById('filesDropdown');
    
    // Sécurité : on vérifie que les deux éléments existent bien sur la page courante
    if (addFilesBtn && filesDropdown) {

        // ===== begin of the code zone generated by Gemini ===
        // Écoute le clic sur le bouton principal
        addFilesBtn.addEventListener('click', (e) => {
            // Empêche le clic de remonter jusqu'au document (ce qui fermerait le menu instantanément)
            e.stopPropagation();
            
            // Vérifie l'état actuel et bascule l'affichage (toggle)
            const isVisible = filesDropdown.style.display === 'block';
            filesDropdown.style.display = isVisible ? 'none' : 'block';
        });
        // ===== end of the code zone generated by Gemini ===

        // Écoute le clic n'importe où ailleurs sur la page pour fermer le menu
        document.addEventListener('click', () => {
            filesDropdown.style.display = 'none';
        });

        // Empêche le menu de se fermer si l'utilisateur clique à l'intérieur de la boîte du menu
        filesDropdown.addEventListener('click', (e) => {
            e.stopPropagation();
        });

    }
});