// Variable globale pour stocker l'identifiant du minuteur de rafraîchissement
let chatInterval = null; 

/**
 * ===== CHARGER UNE CONVERSATION =====
 * Appelé quand on clique sur un musicien à gauche dans la liste
 */
function loadConversation(contactId, name, pseudo, avatar, element) {
    // 1. On arrête le rafraîchissement de la conversation précédente pour éviter les conflits
    if (chatInterval) clearInterval(chatInterval);

    // 2. Mise à jour visuelle de la liste des contacts (gestion de l'état actif)
    document.querySelectorAll('.conv-item').forEach(item => item.classList.remove('active'));
    element.classList.add('active');

    // 3. Rendre l'interface de chat visible (en-tête et zone de saisie)
    document.getElementById('chatHeader').style.display = 'flex';
    document.getElementById('chatFooter').style.display = 'block';

    // 4. Remplir dynamiquement les infos du header avec les données du contact
    document.getElementById('headerAvatar').src = avatar;
    document.getElementById('headerName').innerText = name;
    // On s'assure qu'il n'y a qu'un seul "@" devant le pseudo
    document.getElementById('headerUsername').innerText = "@" + pseudo.replace(/^@/, '');
    document.getElementById('receiverId').value = contactId;

    // 5. Premier appel pour charger immédiatement l'historique des messages
    fetchMessages(contactId);

    // 6. Lancement du "robot" (polling) qui vérifie les nouveaux messages toutes les 3 secondes (3000ms)
    chatInterval = setInterval(() => {
        fetchMessages(contactId);
    }, 3000);

    // Sur mobile, affiche la zone de chat par-dessus la liste
    document.querySelector('.chat-area').classList.add('active');
}

/**
 * ===== RÉCUPÉRER LES MESSAGES =====
 * Interroge le serveur pour récupérer l'historique d'une conversation
 */
function fetchMessages(contactId) {
  const messagesLog = document.getElementById('messagesLog');
  const receiverIdInput = document.getElementById('receiverId');

  // Sécurité : On s'assure qu'on ne rafraîchit que si l'utilisateur est toujours sur la même conversation
  if (receiverIdInput.value != contactId) return;

  fetch(`ajax_get_messages.php?contact_id=${contactId}`)
      .then(response => response.json())
      .then(data => {
          // On compte le nombre de messages actuellement affichés
          const currentDisplayCount = messagesLog.querySelectorAll('.message-node').length;
          
          // Si le nombre de messages a changé (nouveau message reçu ou envoyé), on met à jour l'affichage
          if (data.length !== currentDisplayCount) {
              let html = "";
              
              if (data.length === 0) {
                  html = "<p class='notice-text'>No messages yet. Say hi! 👋</p>";
              } else {
                  // Boucle sur chaque message pour construire le HTML
                  data.forEach(msg => {
                      // On détermine si c'est un message envoyé ou reçu (nécessite que MON_ID soit défini)
                      const type = (msg.sender_id == MON_ID) ? 'outgoing' : 'incoming';
                      
                      // Formatage de l'heure (HH:MM)
                      const date = new Date(msg.created_at);
                      const timeStr = date.getHours() + ":" + date.getMinutes().toString().padStart(2, '0');
                      
                      html += `
                          <div class="message-node ${type}">
                            <div class="message-content">
                              <div class="bubble">${msg.message_text}</div>
                              <div class="message-time">${timeStr}</div>
                            </div>
                          </div>`;
                  });
              }
              
              // Injection du HTML et défilement automatique vers le bas (dernier message)
              messagesLog.innerHTML = html;
              messagesLog.scrollTop = messagesLog.scrollHeight;
          }
      })
      .catch(err => console.error("Erreur :", err));
}

// ===== begin of the code zone generated by Gemini ===

/**
 * ===== ENVOYER UN MESSAGE =====
 */
function sendMessage() {
    const input = document.getElementById('messageInput');
    const text = input.value.trim();
    const toId = document.getElementById('receiverId').value;

    // On bloque l'envoi si le champ est vide ou si on n'a pas de destinataire
    if (!text || !toId) return;

    // Préparation des données pour la requête POST
    const formData = new FormData();
    formData.append('text', text);
    formData.append('to_id', toId);

    fetch('ajax_send_message.php', {
        method: 'POST',
        body: formData
    })
    .then(response => response.json())
    .then(data => {
        if (data.status === 'success') {
            // On vide le champ de saisie une fois le message envoyé
            input.value = "";
            // On force un rafraîchissement immédiat pour afficher notre propre message
            fetchMessages(toId);
        }
    });
}

// ===== end of the code zone generated by Gemini ===


/**
 * ===== AFFICHER UNE BULLE DANS LE LOG (Fonction utilitaire) =====
 * Permet d'injecter une bulle de message directement
 */
function renderMessage(text, time, type) {
    const messagesLog = document.getElementById('messagesLog');
    const msgNode = document.createElement('div');
    msgNode.className = `message-node ${type}`;
    msgNode.innerHTML = `
      <div class="message-content">
        <div class="bubble">${text}</div>
        <div class="message-time">${time}</div>
      </div>
    `;
    messagesLog.appendChild(msgNode);
}

// ===== ÉVÉNEMENTS GLOBAUX =====

// Détecte l'appui sur la touche "Entrée" pour envoyer le message depuis l'input
document.addEventListener('keypress', (e) => {
    if (e.key === 'Enter' && document.activeElement.id === 'messageInput') {
        sendMessage();
    }
});

// ===== begin of the code zone generated by Gemini ===

/**
 * ===== SYSTÈME DE FOLLOW/UNFOLLOW =====
 */
function toggleFollow(userId, btn) {
  const formData = new FormData();
  formData.append('followed_id', userId);

  fetch('ajax_follow.php', {
      method: 'POST',
      body: formData
  })
  .then(response => response.json())
  .then(data => {
      // Mise à jour visuelle du bouton selon la réponse du serveur
      if (data.status === 'followed') {
          btn.innerText = "Followed";
          btn.style.backgroundColor = "#28a745"; // Vert succès
          btn.style.border = "none";
      } else if (data.status === 'removed') {
          btn.innerText = "Connect";
          btn.style.backgroundColor = ""; // Reprend la couleur du CSS par défaut
          btn.style.border = "";
      }
  })
  .catch(err => console.error("Erreur Follow:", err));
}

// ===== end of the code zone generated by Gemini ===


/**
 * ===== FERMER LE CHAT (Mobile) =====
 */
function closeChat() {
    // Masque la zone de chat sur petit écran pour revenir à la liste des contacts
    document.querySelector('.chat-area').classList.remove('active');
}