/**
 * ===== TABS & NAVIGATION =====
 * Gère l'affichage des onglets (Posts, Events, Media)
 */
function switchTab(tabName) {
  // 1. On cache d'abord tous les contenus des onglets
  document.querySelectorAll('.tab-content').forEach(content => 
    content.classList.remove('active')
  );

  // 2. On désactive visuellement tous les boutons
  document.querySelectorAll('.tab-btn').forEach(button => 
    button.classList.remove('active')
  );

  // 3. On affiche uniquement le contenu ciblé et on active son bouton
  const selectedContent = document.getElementById(`${tabName}-section`);
  if (selectedContent) {
    selectedContent.classList.add('active');
    // Utilisation de event.currentTarget pour cibler précisément l'élément cliqué
    if (window.event) window.event.currentTarget.classList.add('active');
  }
}

/**
 * ===== GESTION DE LA MODAL D'ÉDITION =====
 */
function openEditModal() {
  const modal = document.getElementById('edit-profile-modal');
  if (!modal) return;
  
  modal.style.display = 'flex';
  // Petit délai (10ms) pour laisser l'animation CSS d'apparition se déclencher
  setTimeout(() => modal.classList.add('active'), 10);
  // On empêche le défilement de la page en arrière-plan
  document.body.style.overflow = 'hidden'; 
}

function closeEditModal() {
  const modal = document.getElementById('edit-profile-modal');
  if (!modal) return;
  
  modal.classList.remove('active');
  // On attend la fin de l'animation avant de masquer la modal (200ms)
  setTimeout(() => { modal.style.display = 'none'; }, 200);
  // On réactive le défilement de la page
  document.body.style.overflow = '';
}

// Permet de fermer la modal si on clique à l'extérieur de celle-ci (sur le fond sombre)
document.getElementById('edit-profile-modal')?.addEventListener('click', (e) => {
  if (e.target.id === 'edit-profile-modal') closeEditModal();
});

/**
 * ===== PREVIEW DES FICHIERS (AVATAR & BANNIÈRE) =====
 */
function setupFilePreview(inputId, infoId) {
  const input = document.getElementById(inputId);
  const info = document.getElementById(infoId);
  if (!input || !info) return;
  
  // Quand un fichier est sélectionné, on met à jour le texte pour confirmer
  input.addEventListener('change', function() {
    if (this.files?.[0]) {
      info.textContent = `✓ ${this.files[0].name}`;
      info.style.color = '#27ae60'; // Texte en vert pour indiquer le succès
    }
  });
}

/**
 * ===== SOUMISSION DU FORMULAIRE =====
 * Le PHP gère la vraie sauvegarde, on affiche juste un retour visuel (Toast)
 */
function handleProfileUpdate(e) {
  // Attention : on ne fait PAS e.preventDefault() ! 
  // On veut laisser le formulaire partir normalement vers index.php?action=doUpdateProfile
  
  showToast('Saving changes to server...', 'success');
  
  // La page va se recharger toute seule une fois le traitement PHP terminé
}

// ===== begin of the code zone generated by Gemini ===
/**
 * ===== NOTIFICATIONS (TOASTS) =====
 */
function showToast(message, type = 'success') {
  const toast = document.createElement('div');
  toast.className = `toast toast-${type}`;
  
  // Style en ligne pour le toast pour qu'il soit indépendant du fichier CSS global
  toast.style.cssText = `
    position: fixed;
    bottom: 24px;
    right: 24px;
    padding: 14px 24px;
    background: ${type === 'success' ? '#810F29' : '#e74c3c'};
    color: white;
    border-radius: 8px;
    font-weight: 500;
    z-index: 9999;
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
  `;
  toast.textContent = message;
  document.body.appendChild(toast);
  
  // Disparition automatique après 3 secondes (3000ms)
  setTimeout(() => {
    toast.style.opacity = '0';
    toast.style.transition = '0.5s';
    setTimeout(() => toast.remove(), 500); // On retire l'élément du DOM après l'animation
  }, 3000);
}
// ===== end of the code zone generated by Gemini ===

/**
 * ===== INITIALISATION AU CHARGEMENT =====
 */
document.addEventListener('DOMContentLoaded', () => {
  // Initialisation des textes de preview pour les uploads d'images
  setupFilePreview('banner-upload', 'banner-info');
  setupFilePreview('avatar-upload', 'avatar-info');
  
  // On connecte la fonction de soumission visuelle au formulaire d'édition
  const editForm = document.getElementById('edit-profile-form');
  if (editForm) {
    editForm.addEventListener('submit', handleProfileUpdate);
  }
});