<?php
session_start();
// Inclusion du fichier pour la connexion à la base de données
require_once 'class/Database.class.php';

// Vérification que l'utilisateur est connecté et qu'on a bien reçu l'ID de la personne à suivre
if (isset($_SESSION['user_id']) && isset($_POST['followed_id'])) {
    $pdo = Database::getLink();
    $followerId = $_SESSION['user_id'];
    $followedId = $_POST['followed_id'];

    // On vérifie si tu le suis déjà dans la base de données
    $check = $pdo->prepare("SELECT * FROM follows WHERE follower_id = ? AND followed_id = ?");
    $check->execute([$followerId, $followedId]);

    if ($check->fetch()) {
        // Déjà suivi -> On supprime l'enregistrement pour faire un "Unfollow"
        $stmt = $pdo->prepare("DELETE FROM follows WHERE follower_id = ? AND followed_id = ?");
        $stmt->execute([$followerId, $followedId]);
        
        // Retourne un statut JSON pour mettre à jour le bouton côté front-end
        echo json_encode(['status' => 'removed']);
    } else {
// ===== begin of the code zone generated by Gemini ===
        // Pas encore suivi -> On insère une nouvelle ligne (Follow)
        $stmt = $pdo->prepare("INSERT INTO follows (follower_id, followed_id, status) VALUES (?, ?, 'followed')");
        $stmt->execute([$followerId, $followedId]);
        
        echo json_encode(['status' => 'followed']);
// ===== end of the code zone generated by Gemini ===
    }
}