<?php
session_start();
// Inclusion des classes nécessaires
require_once 'class/Database.class.php';
require_once 'class/User.class.php'; 

// Vérification de la session et de la présence de contenu
if (isset($_SESSION['user_id']) && !empty($_POST['content'])) {
    $pdo = Database::getLink();
    $userId = $_SESSION['user_id'];
    $postId = $_POST['post_id'];
    $content = $_POST['content'];

    // Insertion du commentaire en base de données
    $stmt = $pdo->prepare("INSERT INTO comments (post_id, user_id, content) VALUES (?, ?, ?)");
    $stmt->execute([$postId, $userId, $content]);

// ===== begin of the code zone generated by Gemini ===
    // Système de notification
    try {
        // Recherche de l'ID de l'auteur du post
        $stmtAuthor = $pdo->prepare("SELECT user_id FROM posts WHERE id = ?");
        $stmtAuthor->execute([$postId]);
        $postAuthorId = $stmtAuthor->fetchColumn();

        // Si l'auteur n'est pas nous-mêmes, on déclenche la notification
        if ($postAuthorId && $postAuthorId != $userId) {
            $userModel = new User(); 
            
            // On nettoie et on coupe le texte pour l'aperçu dans la table des notifications
            $shortText = mb_strimwidth($content, 0, 50, "..."); 
            
            $userModel->addNotification($postAuthorId, 'comment', $shortText);
        }
    } catch (Exception $e) {
        // En cas d'erreur de la notification, on l'ignore pour ne pas bloquer le JS
    }
// ===== end of the code zone generated by Gemini ===

    // Renvoi des données en JSON pour l'affichage immédiat côté interface
    echo json_encode([
        'status' => 'success',
        'user' => $_SESSION['display_name'] ?? 'Me',
        'content' => htmlspecialchars($content)
    ]);
}