<?php
session_start();
// Inclusion des classes nécessaires pour la base de données et l'utilisateur
require_once 'class/Database.class.php';
require_once 'class/User.class.php'; 

// Vérifie que l'utilisateur est bien connecté et qu'un post_id a été envoyé
if (isset($_SESSION['user_id']) && isset($_POST['post_id'])) {
    $pdo = Database::getLink();
    $userId = $_SESSION['user_id'];
    $postId = $_POST['post_id'];

    // Vérifie dans la base de données si ce post a déjà été liké par cet utilisateur
    $check = $pdo->prepare("SELECT id FROM post_likes WHERE post_id = ? AND user_id = ?");
    $check->execute([$postId, $userId]);
    $existingLike = $check->fetch();

    if ($existingLike) {
        // Le like existe déjà : on le supprime pour faire un "unlike"
        $stmt = $pdo->prepare("DELETE FROM post_likes WHERE post_id = ? AND user_id = ?");
        $stmt->execute([$postId, $userId]);
        
        // Retourne le statut pour mettre à jour l'interface (ex: icône vide)
        echo json_encode(['status' => 'unliked']);
    } else {
        // Le like n'existe pas encore : on l'ajoute dans la table
        $stmt = $pdo->prepare("INSERT INTO post_likes (post_id, user_id) VALUES (?, ?)");
        $stmt->execute([$postId, $userId]);

// ===== begin of the code zone generated by Gemini ===
        // Système de notification
        try {
            // Récupère l'ID de l'auteur du post ciblé
            $stmtAuthor = $pdo->prepare("SELECT user_id FROM posts WHERE id = ?");
            $stmtAuthor->execute([$postId]);
            $postAuthorId = $stmtAuthor->fetchColumn();

            // Envoie une notification seulement si l'auteur n'est pas la personne qui like (pas d'auto-notif)
            if ($postAuthorId && $postAuthorId != $userId) {
                $userModel = new User();
                $userModel->addNotification($postAuthorId, 'like');
            }
        } catch (Exception $e) {
            // Si l'envoi de la notification échoue, on ignore l'erreur pour ne pas bloquer le Like
        }
// ===== end of the code zone generated by Gemini ===

        // Retourne le statut pour mettre à jour l'interface (ex: icône remplie)
        echo json_encode(['status' => 'liked']);
    }
}