<?php
session_start();

ini_set('display_errors', 1);
error_reporting(E_ALL);

// Liste des actions publiques
$actions_publiques = [
    'connexion', 'inscription', 'doConnect', 'doRegister', 'doGoogleLogin', 
    'home', 'about', 'legal', 'terms', 'privacy', 'faq'
];

$action = $_GET['action'] ?? 'home'; 

// Sécurité
if (!in_array($action, $actions_publiques) && !isset($_SESSION['user_id'])) {
    header("Location: index.php?action=connexion");
    exit();
}

// Gestion des langues
if (isset($_GET['lang'])) {
    $_SESSION['lang'] = $_GET['lang'];
    $langue = $_GET['lang']; 
} else {
    $langue = $_SESSION['lang'] ?? 'en';
}

$chemin_fichier = __DIR__ . "/lang/" . $langue . ".php";
$trad = file_exists($chemin_fichier) ? require $chemin_fichier : require __DIR__ . "/lang/en.php";
$GLOBALS['trad'] = $trad;

if (isset($_GET['lang']) && isset($_GET['action'])) {
    header("Location: index.php?action=" . $_GET['action']);
    exit();
}

require_once 'inc/poo.inc.php';
$userModel = new User();

// Routeur principal
switch ($action) {

    case 'home':
        $vue = new VueHome();
        $vue->afficher();
        break;

    case 'explore':
        $vue = new VueExplore();
        $vue->setActionActive('explore'); 
        $vue->afficher();
        break;

    case 'agenda':
        $vue = new VueAgenda();
        $vue->setActionActive('agenda'); 
        $vue->afficher();
        break;

    case 'profile':
        $vue = new VueProfil();
        $vue->setActionActive('profile');
        $vue->afficher();
        break;

// ===== begin of the code zone generated by Gemini ===
    case 'doUpdateProfile':
        if (isset($_SESSION['user_id'])) {
            $pdo = Database::getLink();
            $uid = $_SESSION['user_id'];
    
            $sql = "UPDATE users SET 
                    display_name = :name, 
                    bio = :bio, 
                    city = :city,
                    languages = :langs 
                    WHERE id = :id";
            
            $stmt = $pdo->prepare($sql);
            $stmt->execute([
                ':name'    => $_POST['display_name'],
                ':bio'     => $_POST['bio'],
                ':city'    => $_POST['city'] ?? '',
                ':langs'   => $_POST['languages'] ?? '', 
                ':id'      => $uid
            ]);
    
            // Gestion de l'Avatar
            if (!empty($_FILES['profile_pic']['name'])) {
                $ext = strtolower(pathinfo($_FILES['profile_pic']['name'], PATHINFO_EXTENSION));
                $path = "img/profiles/avatar_" . $uid . "_" . time() . "." . $ext;
                if (move_uploaded_file($_FILES['profile_pic']['tmp_name'], $path)) {
                    $pdo->prepare("UPDATE users SET profile_pic = :p WHERE id = :id")
                        ->execute([':p' => $path, ':id' => $uid]);
                    $_SESSION['profile_pic'] = $path;
                }
            }
    
            // Gestion de la Bannière
            if (!empty($_FILES['banner_pic']['name'])) {
                $ext = strtolower(pathinfo($_FILES['banner_pic']['name'], PATHINFO_EXTENSION));
                $path = "img/banners/banner_" . $uid . "_" . time() . "." . $ext;
                if (move_uploaded_file($_FILES['banner_pic']['tmp_name'], $path)) {
                    $pdo->prepare("UPDATE users SET banner_pic = :p WHERE id = :id")
                        ->execute([':p' => $path, ':id' => $uid]);
                    $_SESSION['banner_pic'] = $path;
                }
            }

            $_SESSION['display_name'] = $_POST['display_name'];
            $_SESSION['bio']          = $_POST['bio'];
            $_SESSION['languages']    = $_POST['languages'] ?? '';
        }
        
        header("Location: index.php?action=profile");
        exit();
        break;
// ===== end of the code zone generated by Gemini ===

    case 'deletePost':
        if (isset($_GET['id']) && isset($_SESSION['user_id'])) {
            $pdo = Database::getLink();
            $stmt = $pdo->prepare("DELETE FROM posts WHERE id = ? AND user_id = ?");
            $success = $stmt->execute([(int)$_GET['id'], $_SESSION['user_id']]);
            
            header('Content-Type: application/json');
            echo json_encode(['success' => $success]);
            exit();
        }
        break;

    case 'feed':
        $vue = new VueFeed();
        $vue->setActionActive('feed');
        $vue->afficher();
        break;

    case 'messages':
        $vue = new VueMessages();
        $vue->setActionActive('messages');
        $vue->afficher();
        break;

    case 'notif':
        $vue = new VueNotif();
        $vue->setActionActive('notif');
        $vue->afficher();
        break;

    case 'follow':
        $tab = $_GET['tab'] ?? 'following'; 
        $vue = new VueFollow([], $tab);
        $vue->setActionActive('follow');
        $vue->afficher();
        break;

    case 'saveEvent':
        if (isset($_POST['title'])) {
            $pdo = Database::getLink();
            $id = !empty($_POST['id']) ? (int)$_POST['id'] : null;
            $start_date = $_POST['date'] . ' ' . $_POST['start_time'];
            $end_date = $_POST['date'] . ' ' . $_POST['end_time'];
            $myId = $_SESSION['user_id'];

            if ($id) {
                $sql = "UPDATE events SET title = ?, description = ?, start_date = ?, end_date = ?, visibility = ? WHERE id = ? AND creator_id = ?";
                $pdo->prepare($sql)->execute([$_POST['title'], $_POST['description'], $start_date, $end_date, $_POST['visibility'], $id, $myId]);
            } else {
                $sql = "INSERT INTO events (creator_id, title, description, start_date, end_date, visibility) VALUES (?, ?, ?, ?, ?, ?)";
                $pdo->prepare($sql)->execute([$myId, $_POST['title'], $_POST['description'], $start_date, $end_date, $_POST['visibility']]);
            }
        }
        header("Location: index.php?action=agenda");
        exit();
        break;

    case 'deleteEvent':
        if (isset($_GET['id'])) {
            $pdo = Database::getLink();
            $id = (int)$_GET['id'];
            $myId = $_SESSION['user_id'];
            $pdo->prepare("DELETE FROM events WHERE id = ? AND creator_id = ?")->execute([$id, $myId]);
        }
        header("Location: index.php?action=agenda");
        exit();
        break;

    case 'doFollow':
        $id_cible = isset($_GET['id']) ? (int)$_GET['id'] : 0;
        $mon_id = $_SESSION['user_id'] ?? 0;
        if ($id_cible > 0 && $mon_id > 0) {
            $pdo = Database::getLink();
            $pdo->prepare("INSERT IGNORE INTO follows (follower_id, followed_id) VALUES (?, ?)")->execute([$mon_id, $id_cible]);
            $userModel->addNotification($id_cible, 'follow');
            header("Location: " . ($_SERVER['HTTP_REFERER'] ?? 'index.php?action=follow'));
            exit();
        }
        break;

    case 'doUnfollow':
        $id_cible = isset($_GET['id']) ? (int)$_GET['id'] : 0;
        $mon_id = $_SESSION['user_id'] ?? 0;
        
        if ($id_cible > 0 && $mon_id > 0) {
            $pdo = Database::getLink();
            $sql = "DELETE FROM follows WHERE follower_id = ? AND followed_id = ?";
            $stmt = $pdo->prepare($sql);
            $stmt->execute([$mon_id, $id_cible]);
        }
        header("Location: " . ($_SERVER['HTTP_REFERER'] ?? 'index.php?action=follow'));
        exit();
        break;

    case 'doLike':
        if (isset($_GET['post_id']) && isset($_SESSION['user_id'])) {
            $post_id = (int)$_GET['post_id'];
            $mon_id = $_SESSION['user_id'];
            $pdo = Database::getLink();
            $stmt = $pdo->prepare("SELECT user_id FROM posts WHERE id = ?");
            $stmt->execute([$post_id]);
            $id_auteur = $stmt->fetchColumn();
            $pdo->prepare("INSERT IGNORE INTO post_likes (post_id, user_id) VALUES (?, ?)")->execute([$post_id, $mon_id]);
            if ($id_auteur && $id_auteur != $mon_id) $userModel->addNotification($id_auteur, 'like');
            header("Location: " . ($_SERVER['HTTP_REFERER'] ?? 'index.php?action=feed'));
            exit();
        }
        break;

    case 'doComment':
        if (isset($_POST['post_id']) && !empty($_POST['content'])) {
            $post_id = (int)$_POST['post_id'];
            $content = htmlspecialchars($_POST['content']);
            $mon_id = $_SESSION['user_id'];
            $pdo = Database::getLink();
            $stmt = $pdo->prepare("SELECT user_id FROM posts WHERE id = ?");
            $stmt->execute([$post_id]);
            $id_auteur = $stmt->fetchColumn();
            $pdo->prepare("INSERT INTO comments (post_id, user_id, content, created_at) VALUES (?, ?, ?, NOW())")->execute([$post_id, $mon_id, $content]);
            if ($id_auteur && $id_auteur != $mon_id) $userModel->addNotification($id_auteur, 'comment', mb_strimwidth($content, 0, 50, "..."));
            header("Location: " . $_SERVER['HTTP_REFERER']);
            exit();
        }
        break;

    case 'connexion':
        $vue = new VueAuth();
        $vue->afficherConnexion();
        break;

    case 'doConnect':
        if ($userModel->connecter($_POST['email'], $_POST['pass'])) {
            header("Location: index.php?action=explore");
        } else {
            header("Location: index.php?action=connexion&error=1");
        }
        exit();

    case 'inscription':
        $vue = new VueAuth();
        $vue->afficherInscription($_GET['error'] ?? null); 
        break;

    case 'doRegister':
        $res = $userModel->inscrire($_POST, $_FILES);
        if ($res === "success") {
            header("Location: index.php?action=connexion&reg=ok");
        } else {
            header("Location: index.php?action=inscription&error=" . urlencode($res));
        }
        exit();

    case 'doGoogleLogin':
        if (!empty($_POST['email'])) {
            $userModel->connecterViaGoogle(['email' => $_POST['email'], 'name' => $_POST['name'] ?? '', 'picture' => $_POST['picture'] ?? '']);
            echo "success"; 
        }
        break;

    case 'logout':
        session_destroy();
        header("Location: index.php?action=connexion");
        exit();

    case 'legal': (new VueLegal())->afficher(); break;
    case 'terms': (new VueTerms())->afficher(); break;
    case 'privacy': (new VuePrivacy())->afficher(); break;
    case 'faq': (new VueFAQ())->afficher(); break;
    case 'about': (new VueAbout())->afficher(); break;
    case 'vinyl': (new VueVinyl())->afficher(); break;


    default:
        $vue = new VueHome();
        $vue->afficher();
        break;
}