<?php
class User {

    /**
     * Récupère les coordonnées GPS via OpenStreetMap (Nominatim)
     */

     // ===== begin of the code zone generated by Gemini ===

     public function addNotification($target_user_id, $type, $content = null) {
        $pdo = Database::getLink();
        $source_id = $_SESSION['user_id'] ?? 0;
    
        // IMPORTANT : On force le format "Nombre Entier"
        $target = (int)$target_user_id;
        $source = (int)$source_id;
    
        if ($target <= 0 || $source <= 0) return false;
    
        $sql = "INSERT INTO notifications (user_id, type, source_id, content, is_read, created_at) 
                VALUES (:target, :type, :source, :content, 0, NOW())";
        
        $stmt = $pdo->prepare($sql);
        return $stmt->execute([
            ':target'  => $target,
            ':type'    => $type,
            ':source'  => $source,
            ':content' => $content
        ]);
    }
    // ===== end of the code zone generated by Gemini ===



    private function getCoordinates($city, $country) {
        $address = urlencode($city . ", " . $country);
        $url = "https://nominatim.openstreetmap.org/search?format=json&q=$address&limit=1";
    
        $opts = [
            "http" => [
                "method" => "GET",
                "header" => "User-Agent: LinkUp-App-Project\r\n"
            ]
        ];
        $context = stream_context_create($opts);
        $response = @file_get_contents($url, false, $context);
        $data = json_decode($response, true);
    
        if (!empty($data)) {
            return [
                'lat' => $data[0]['lat'],
                'lng' => $data[0]['lon']
            ];
        }
        return ['lat' => 0, 'lng' => 0]; // Valeurs par défaut si non trouvé
    }
    
    private function existeDeja($colonne, $valeur) {
        $pdo = Database::getLink();
        $sql = "SELECT COUNT(*) FROM users WHERE $colonne = ?";
        $stmt = $pdo->prepare($sql);
        $stmt->execute([$valeur]);
        return $stmt->fetchColumn() > 0;
    }

    // ===== begin of the code zone generated by Gemini ===

    private function isPasswordSecure($password) {
        // 8 caractères, 1 Majuscule, 1 Caractère spécial
        return strlen($password) >= 8 
               && preg_match('/[A-Z]/', $password) 
               && preg_match('/[^a-zA-Z0-9]/', $password);
    }

    // ===== end of the code zone generated by Gemini ===


    public function inscrire($data, $files) {
        // 1. Nettoyage du pseudo
        $pseudo = trim($data["pseudo"] ?? "");
        if (empty($pseudo)) return "Pseudo is required.";
        $pseudo = str_replace(["@", " "], ["", "_"], $pseudo);

        // 2. Vérification des doublons
        if ($this->existeDeja("email", $data["email"])) return "This email address is already registered.";
        if ($this->existeDeja("pseudo", $pseudo)) return "This pseudo is already taken.";

        // 3. Sécurité mot de passe
        if (!$this->isPasswordSecure($data["pass"])) {
            return "Password insecure: 8 chars min, 1 uppercase and 1 special char required.";
        }

        // 4. Géocodage conditionnel (MODIFIÉ)
        $city = $data["city"] ?? "";
        $country = $data["country"] ?? "";
        
        // Par défaut, on met à 0
        $lat = 0;
        $lng = 0;

        // On ne récupère et n'enregistre les coordonnées QUE si la case est cochée
        if (isset($data["share_location"]) && $data["share_location"] == "1") {
            $coords = $this->getCoordinates($city, $country);
            $lat = $coords["lat"];
            $lng = $coords["lng"];
        }

        // 5. Gestion des images par défaut
        $profile_pic = "img/photo_defaut.png";
        $banner_pic  = "img/banniere_defaut.png";

        if (!empty($files["profile_pic"]["name"])) {
            $ext = pathinfo($files["profile_pic"]["name"], PATHINFO_EXTENSION);
            $filename = time() . "_" . $pseudo . "." . $ext;
            $target_path = "img/profiles/" . $filename;

            if (move_uploaded_file($files["profile_pic"]["tmp_name"], $target_path)) {
                $profile_pic = $target_path; 
            }
        }

        $languages = $data["languages"] ?? ""; // Récupère la chaîne "Français,English"

        try {
    $pdo = Database::getLink();
    $hash = password_hash($data["pass"], PASSWORD_DEFAULT);
    
    // AJOUT DE "languages" DANS LES COLONNES ET LES VALUES
    $sql = "INSERT INTO users (email, password, display_name, pseudo, bio, city, country, lat, lng, languages, profile_pic, banner_pic, created_at) 
            VALUES (:email, :pass, :name, :pseudo, :bio, :city, :country, :lat, :lng, :langs, :p_pic, :b_pic, NOW())";
    
    $stmt = $pdo->prepare($sql);
    $stmt->execute([
        ":email"   => htmlspecialchars($data["email"]),
        ":pass"    => $hash,
        ":name"    => htmlspecialchars($data["display_name"]),
        ":pseudo"  => htmlspecialchars($pseudo),
        ":bio"     => htmlspecialchars($data["bio"] ?? ""),
        ":city"    => htmlspecialchars($city),
        ":country" => htmlspecialchars($country),
        ":lat"     => $lat,
        ":lng"     => $lng,
        ":langs"   => htmlspecialchars($languages), // ON ENREGISTRE ICI
        ":p_pic"   => $profile_pic,
        ":b_pic"   => $banner_pic
    ]);
    return "success";
} catch (PDOException $e) {
    return "A database error occurred: " . $e->getMessage();
}
    }

    public function connecter($email, $mdp) {
        $pdo = Database::getLink();
        $sql = "SELECT * FROM users WHERE email = :email";
        $stmt = $pdo->prepare($sql);
        $stmt->execute([':email' => $email]);
        $user = $stmt->fetch();
    
        if ($user && password_verify($mdp, $user['password'])) {
            $this->setSession($user);
            return true; 
        }
        return false; 
    }

    /**
     * Factorisation de la mise en session
     */
    // ===== begin of the code zone generated by Gemini ===

    private function setSession($user) {
        $_SESSION['user_id']       = $user['id'];
        $_SESSION['languages']   = $user['languages'] ?? ''; 
        $_SESSION['user_email']    = $user['email'];
        $_SESSION['display_name']  = $user['display_name'];
        $_SESSION['pseudo']        = $user['pseudo'];
        $_SESSION['bio']           = $user['bio'] ?? '';
        $_SESSION['city']          = $user['city'] ?? '';
        $_SESSION['country']       = $user['country'] ?? '';
        $_SESSION['lat']           = $user['lat'] ?? 0;
        $_SESSION['lng']           = $user['lng'] ?? 0;
        $_SESSION['profile_pic']   = $user['profile_pic'];
        $_SESSION['banner_pic']    = $user['banner_pic'];
        $_SESSION['created_at']    = $user['created_at'];
    }
    // ===== end of the code zone generated by Gemini ===


    public function connecterViaGoogle($data) {
        $pdo = Database::getLink();
        $sql = "SELECT * FROM users WHERE email = :email";
        $stmt = $pdo->prepare($sql);
        $stmt->execute([':email' => $data['email']]);
        $user = $stmt->fetch();
    
        if (!$user) {
            $basePseudo = strtolower(str_replace(' ', '_', $data['name'])); 
            $pseudo = $basePseudo . '_' . rand(100, 999);

            $sql = "INSERT INTO users (email, display_name, pseudo, profile_pic, banner_pic, created_at) 
                    VALUES (:email, :name, :pseudo, :pic, 'img/banniere_defaut.png', NOW())";
            $stmt = $pdo->prepare($sql);
            $stmt->execute([
                ':email'  => $data['email'],
                ':name'   => $data['name'],
                ':pseudo' => $pseudo,
                ':pic'    => $data['picture'] 
            ]);
            
            $newId = $pdo->lastInsertId();
            $stmt = $pdo->prepare("SELECT * FROM users WHERE id = ?");
            $stmt->execute([$newId]);
            $user = $stmt->fetch();
        }
    
        $this->setSession($user);
        return true;
    }
}