<?php

class VueFollow extends VueBase
{
    private $tab;

    public function __construct($users = [], $tab = 'following')
    {
        parent::__construct("Connect - LinkUp");
        $this->tab = $tab;
        $this->actionActive = 'follow'; 
    }

    // ===== begin of the code zone generated by Gemini ===

    private function getRealMusicians()
    {
        $pdo = Database::getLink();
        $myId = $_SESSION['user_id'];

        if ($this->tab === 'followers') {
            $sql = "SELECT u.* FROM users u 
                    INNER JOIN follows f ON u.id = f.follower_id 
                    WHERE f.followed_id = ?";
        } else {
            $sql = "SELECT u.* FROM users u 
                    INNER JOIN follows f ON u.id = f.followed_id 
                    WHERE f.follower_id = ?";
        }

        $stmt = $pdo->prepare($sql);
        $stmt->execute([$myId]);
        return $stmt->fetchAll();
    }

    // ===== end of the code zone generated by Gemini ===


    public function afficher()
    {
        $musiciansFromDb = $this->getRealMusicians();

        $followingActive = $this->tab === 'following' ? 'kb-explore-tabs__item--active' : '';
        $followersActive = $this->tab === 'followers' ? 'kb-explore-tabs__item--active' : '';

        ob_start(); 
        ?>
        
        <link rel="stylesheet" href="css/style.css">
        <link rel="stylesheet" href="css/follow.css">

        <section class="kb-explore-page">
            <div class="kb-page-heading">
                <h1 class="kb-page-heading__title">My Connections</h1>
                <p class="kb-page-heading__subtitle">Manage your musical network and collaborators.</p>
            </div>

            <div class="kb-explore-tabs">
                <a href="index.php?action=follow&tab=following" class="kb-explore-tabs__item <?= $followingActive ?>">Following</a>
                <a href="index.php?action=follow&tab=followers" class="kb-explore-tabs__item <?= $followersActive ?>">Followers</a>
            </div>

            

            <div class="kb-explore-layout">
                <div class="kb-explore-grid">
                    <?php if (empty($musiciansFromDb)): ?>
                        <p style="grid-column: 1/-1; text-align: center; padding: 50px; color: #666;">
                            No musicians found in this section.
                        </p>
                    <?php else: ?>
                        <?php foreach ($musiciansFromDb as $m): 
                            $name = htmlspecialchars($m['display_name']);
                            $pseudo = "@" . htmlspecialchars($m['pseudo']);
                            $bio = htmlspecialchars($m['bio'] ?? "Ready to jam!");
                            $avatar = !empty($m['profile_pic']) ? $m['profile_pic'] : 'img/ppMan.png';
                            
                            $locRaw = $m['city'] ?? 'Unknown';
                            $parts = explode(',', $locRaw);
                            $location = (count($parts) > 1) ? trim($parts[0]) . ', ' . trim(end($parts)) : $locRaw;
                        ?>
                            <article class="kb-musician-card">
                                <div class="kb-musician-card__top">
                                    <div class="kb-musician-card__identity">
                                        <img src="<?= $avatar ?>" class="kb-musician-card__avatar" style="width:50px; height:50px; border-radius:50%; object-fit:cover;">
                                        <div class="kb-musician-card__meta">
                                            <h3 class="kb-musician-card__name"><?= $name ?></h3>
                                            <p class="kb-musician-card__username"><?= $pseudo ?></p>
                                            <p class="kb-musician-card__location">
                                                <img src="img/pin.png" alt="pin" style="width:10px;"> <?= htmlspecialchars($location) ?>
                                            </p>
                                        </div>
                                    </div>

                                    <?php if ($this->tab === 'following'): ?>
                                        <button class="kb-follow-button unfollow-style" 
                                                onclick="if(confirm('Unfollow <?= $name ?>?')) window.location.href='index.php?action=doUnfollow&id=<?= $m['id'] ?>'"
                                                onmouseover="this.innerText='Unfollow'; this.style.background='#dc3545'"
                                                onmouseout="this.innerText='Following'; this.style.background='#28a745'">
                                            Following
                                        </button>
                                    <?php endif; ?>
                                    </div>

                                <p class="kb-musician-card__description"><?= $bio ?></p>

                                <div class="kb-musician-card__tags">
                                    <span class="kb-tag">#Artist</span>
                                    <span class="kb-tag">#LinkUp</span>
                                </div>
                            </article>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>

            

        </section>

        <style>
            /* Style dynamique pour le bouton Following/Unfollow */
            .unfollow-style {
                background: #28a745; 
                color: white; 
                border: none; 
                min-width: 100px;
                transition: all 0.2s ease;
            }
        </style>

        <?php
        
        $this->contenu = ob_get_clean();
        parent::afficher();
    }
}