<?php

class VueNotif extends VueBase
{
    public function __construct()
    {
        parent::__construct("Notifications - LinkUp");
        $this->actionActive = 'notifications';
    }

    // ===== begin of the code zone generated by Gemini ===

    private function getRealNotifications()
    {
        $pdo = Database::getLink();
        $myId = $_SESSION['user_id'] ?? 0;

        $sql = "SELECT n.*, u.display_name, u.pseudo, u.profile_pic 
                FROM notifications n
                JOIN users u ON n.source_id = u.id
                WHERE n.user_id = :my_id
                ORDER BY n.created_at DESC";

        $stmt = $pdo->prepare($sql);
        $stmt->execute([':my_id' => $myId]);
        return $stmt->fetchAll();
    }

    // ===== end of the code zone generated by Gemini ===

    private function formatNotifText($n) {
        if ($n['type'] === 'follow') return "started following you.";
        if ($n['type'] === 'like') return "liked your post.";
        if ($n['type'] === 'comment') {
            $commentaire = !empty($n['content']) ? $n['content'] : "...";
            return "commented on your post: \"" . $commentaire . "\"";
        }

        $texts = [
            'mention' => 'mentioned you in a post.',
            'event'   => 'invited you to an event.',
            'message' => 'sent you a private message.'
        ];
        return $texts[$n['type']] ?? 'interacted with you.';
    }

    private function timeAgo($timestamp) {
        $diff = time() - strtotime($timestamp);
        if ($diff < 60) return "Just now";
        if ($diff < 3600) return round($diff / 60) . " min ago";
        if ($diff < 86400) return round($diff / 3600) . " hours ago";
        return date('d M', strtotime($timestamp));
    }

    public function afficher()
    {
        $notifications = $this->getRealNotifications();

        ob_start(); 
        ?>
        
        <link rel="stylesheet" href="css/style.css">
        <link rel="stylesheet" href="css/notif.css">

        

        <section class="kb-notifications-page">
            <div class="kb-page-heading">
                <h1 class="kb-page-heading__title">Notifications</h1>
                <p class="kb-page-heading__subtitle">Stay updated with activity from your music community.</p>
            </div>

            <div class="kb-notifications-card">
                <?php if (empty($notifications)): ?>
                    <div style="padding: 40px; text-align: center;">
                        <p style="color: #666;">No notifications for the moment. Get out there and connect!</p>
                    </div>
                <?php else: ?>
                    <?php foreach ($notifications as $n): 
                        $notificationClass = ($n['is_read'] == 0) ? 'kb-notification kb-notification--unread' : 'kb-notification';
                    ?>
                        <article class="<?= $notificationClass ?>" style="cursor: default;">
                            <div class="kb-notification__left">
                                <img src="<?= !empty($n['profile_pic']) ? $n['profile_pic'] : 'img/photo_defaut.png' ?>" 
                                     alt="avatar" 
                                     style="width: 45px; height: 45px; border-radius: 50%; object-fit: cover; margin-right: 15px;">
                                
                                <div class="kb-notification__content">
                                    <p class="kb-notification__text">
                                        <strong><?= htmlspecialchars($n['display_name']) ?></strong>
                                        <span class="kb-notification__username">@<?= htmlspecialchars($n['pseudo']) ?></span>
                                        <?= htmlspecialchars($this->formatNotifText($n)) ?>
                                    </p>
                                    <p class="kb-notification__time"><?= $this->timeAgo($n['created_at']) ?></p>
                                </div>
                            </div>
                            
                            </article>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </section>

        

        <?php
        $this->contenu = ob_get_clean();
        parent::afficher();
    }
}